### ISSUE TITLE
Bug: Lootsplosions do not have particle effects on tiered items from MMOItems.

### ISSUE THREAD

**Issue by AshenGaming** [Indyuce/mmocore#13]
**Describe the bug**
Lootsplosions do not appear to display any particles when dropping a tiered item from MMOItems.

**To Reproduce**
1. Add a tiered item to be dropped via a MythicMobs dropTable to a MythicMob.
2. Kill the mob with lootsplosions enabled in the MMOCore config.

**Expected behavior**
Any items without a tier should drop with no particle effect, whereas the tiered item should have a particle effect matching the colour set in the tier config.

**Screenshots**
Here are some screenshots of the item in inventory with a tier, and a screenshot showing no particles.
https://i.imgur.com/iOsLEJT.png
https://i.imgur.com/2a7gc5e.png

**Plugin Information:**
 - Plugins involved: MythicMobs 4.8.0, MMOCore 1.0.13, MMOItems 4.7.21
 - Server Version PaperMC 1.14.4

**Comment by Indyuce** [comment]
I have updated the wiki, check the bottom of this page. Items must have a glow color.
https://github.com/Indyuce/mmocore/wiki/Lootsplosions/
