### ISSUE TITLE
just a few missing GUI translation

### ISSUE THREAD

**Issue by aaa8881** [Indyuce/mmocore#2]
/party GUI , GUI-name 
/friends GUI, GUI-name
Friends Removal Confirmation GUI, GUI-name, yes and no Item name 

Translation options that exist, but does not apply
no_booster ( items.yml )

Translations that do not exist 
Switch to Binding ( /skill )
Switch to Upgrade ( /skill )
None ( lore of slot at /skill , when none is bound to a slot )

**Comment by Indyuce** [comment]
Currently being worked on
