### ISSUE TITLE
BUG - Can't add mmoitem reward to quests triggers

### ISSUE THREAD

**Issue by monohito** [Indyuce/mmocore#24]
i cannot completed quests when i add mmoitem reward to quests triggers,
the server control panel will show this error :

![1](https://user-images.githubusercontent.com/61873232/76678665-9ac1e980-6614-11ea-8d11-60b8ce26a725.jpg)

if i delete mmoitem reward in quests triggers, can completed the quests and no this error

this is my quests config triggers:
![2](https://user-images.githubusercontent.com/61873232/76678677-b0cfaa00-6614-11ea-856b-531584f462c1.jpg)

**Comment by Indyuce** [comment]
Seems to work fine with latest dev builds of MMOCore and MMOItems. Can you pastebin your entire server logs that include the error?
