### ISSUE TITLE
disable hologram text?

### ISSUE THREAD

**Issue by thetrollplay** [Indyuce/mmocore#25]
having an issue with hologram text not vanishing and getting spammed with +0.1... after a while there is so many holograms floating, the server is bogged down to the point nothing can be done. the text is nice, but would really like to just disable it and do not see any place this could be done... the only mention i see relates to exp...

this is a major road block for me and really hope someone can help me out. thanks

**Comment by monohito** [comment]
hp hologram text setting in the mmoitems config  
(game-indicators:)
if you need disable it , please change heal to false 
![1](https://user-images.githubusercontent.com/61873232/76815047-7a25a980-6837-11ea-9cc3-67e2148a17d8.PNG)

**Comment by Indyuce** [comment]
Make sure you disable both damage and heal indicators and reload your server afterwars. If you have MMOItems installed, it has the same feature so you might make sure it is disabled there as well.
