### ISSUE TITLE
@ Selectors do not work with MMOCore/MMOItems

### ISSUE THREAD

**Issue by CraftyLemon** [Indyuce/mmocore#32]
so im trying to set up a way for a player to earn a Class point via command console - but unable to get this to use @ selectors that are built in to minecraft, mmocore does not recognise these

so my example would be : 

/mmocore admin class-points give @p 1 
When ran in a command block the output is 

"there is no player named give"

Have tested with generic commands such as </give @ a command_block 1> and this works

Can you add the Functionally if possible   

Have tested with a blank Spigot server and just mmocore in, same issue

**Comment by Indyuce** [comment]
@p only works in vanilla commands. You will need to execute this command using an extra plugin that adds @ support to all commands. Someone reported this issue a while ago and I believe we found some plugin that does that but I don't remember, I'll keep the ticket open and get back to you if I find any

**Comment by CraftyLemon** [comment]
Thank you for your speedy reply after doing a more detailed search i think i found what you were referencing <https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/updates>

Thank you again and love your work
