### ISSUE TITLE
Block regen does not persist over server restarts. 

### ISSUE THREAD

**Issue by iMxAndyy** [Indyuce/mmocore#34]
When blocks are broken and are set to regenerate after an amount of time. If the server is restarted or crashes while the regen timer is running, the timer is cancelled but the blocks never regen. 

A potential solution to this would be to instantly regenerate all running timers when the server is restarted, so that all blocks are reset when it comes back up. (this won't solve the issue if the server crashes)

Or the blocks that are in the process of regenerating could be written to file and removed when they regen. and on server start, read the file to see if any failed to regenerate, and then regenerate them at server start (or continue the timer if you want to write that to file too)

**Comment by Indyuce** [comment]
That issue should be fixed in recent MMOCore dev builds
