### ISSUE TITLE
way to manipulate mana and stellium via command

### ISSUE THREAD

**Issue by aaa8881** [Indyuce/mmocore#7]
might be nice to have a command to manipulate mana and stellium via command such as /mmocore mana <value> <player> , and /mmocore stellium <value> <player>,  accepting value as integer including negative value.

**Comment by Indyuce** [comment]
What could it be used for?

**Comment by aaa8881** [comment]
maybe someone including me might wanna use these ( mana and stellium ) outside of mmocore. For example, I can make a button that consumes 10 stellium and gives regeneration 2 buff for 1 minutes to a player.

**Comment by Indyuce** [comment]
Then you would need to check if the player's stellium is at least 10, which could be done much more easily using the plugin API; I'm not a fan of that type of command.

**Comment by aaa8881** [comment]
I'm not very sure why it's quite different from other rpg admin commands , such as manipulating skill points, class points, or exp, but if you say so - what can I do.  ¯\_(ツ)_/¯

**Comment by Indyuce** [comment]
Just learnt about PAPI conditions and stuff like that which can be done without using a java addon, so after all I'll be implementing many other admin commands including this one.
