### ISSUE TITLE
MMOCore and MMOItem Console Spam

### ISSUE THREAD

**Issue by EtherGamer** [Indyuce/mmocore#8]
I was getting these messages in my console and it was the only thing I see every time.
https://pastebin.com/MZQCPY0t

It only happens when an NPC killed an entity or my example "Zombie", is this a normal problem or it's really not compatible with the **Citizen and Sentinel** plugins?

**Comment by dutchboyyzzz** [comment]
Its compatible with citizen, i use that too, but i dont use sentinals, so cant say anything bout that

**Comment by dibbomarco** [comment]
sentinals spams a lot by default you must evitate this with a mythicmobs faction like Guard, with denydamage from player
